name: Corehub CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm i

      # Run linter
      - name: Run Linter
        run: npm run lint

      # Check Prettier
      - name: Check Prettier
        run: npm run format

      # Run tests
      - name: Run Tests
        run: npm run test

      # Run build
      - name: Run Tests
        run: npm run build
